// Code generated by "stringer -type TokenType"; DO NOT EDIT.

package frontend

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[illegal-0]
	_ = x[identifier-1]
	_ = x[ifKeyword-2]
	_ = x[elseKeyword-3]
	_ = x[varKeyword-4]
	_ = x[constKeyword-5]
	_ = x[funcKeyword-6]
	_ = x[forKeyword-7]
	_ = x[inKeyword-8]
	_ = x[breakKeyword-9]
	_ = x[continueKeyword-10]
	_ = x[returnKeyword-11]
	_ = x[integerLiteral-12]
	_ = x[floatLiteral-13]
	_ = x[stringLiteral-14]
	_ = x[booleanLiteral-15]
	_ = x[nullLiteral-16]
	_ = x[equal-17]
	_ = x[equalEqual-18]
	_ = x[bang-19]
	_ = x[bangEqual-20]
	_ = x[gt-21]
	_ = x[gte-22]
	_ = x[lt-23]
	_ = x[lte-24]
	_ = x[and-25]
	_ = x[or-26]
	_ = x[plus-27]
	_ = x[minus-28]
	_ = x[star-29]
	_ = x[slash-30]
	_ = x[percent-31]
	_ = x[lparen-32]
	_ = x[rparen-33]
	_ = x[lbracket-34]
	_ = x[rbracket-35]
	_ = x[lbrace-36]
	_ = x[rbrace-37]
	_ = x[comma-38]
	_ = x[semicolon-39]
	_ = x[colon-40]
	_ = x[dot-41]
	_ = x[ellipsis-42]
	_ = x[increment-43]
	_ = x[decrement-44]
	_ = x[eof-45]
	_ = x[comment-46]
}

const _TokenType_name = "illegalidentifierifKeywordelseKeywordvarKeywordconstKeywordfuncKeywordforKeywordinKeywordbreakKeywordcontinueKeywordreturnKeywordintegerLiteralfloatLiteralstringLiteralbooleanLiteralnullLiteralequalequalEqualbangbangEqualgtgteltlteandorplusminusstarslashpercentlparenrparenlbracketrbracketlbracerbracecommasemicoloncolondotellipsisincrementdecrementeofcomment"

var _TokenType_index = [...]uint16{0, 7, 17, 26, 37, 47, 59, 70, 80, 89, 101, 116, 129, 143, 155, 168, 182, 193, 198, 208, 212, 221, 223, 226, 228, 231, 234, 236, 240, 245, 249, 254, 261, 267, 273, 281, 289, 295, 301, 306, 315, 320, 323, 331, 340, 349, 352, 359}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
