// Code generated by "stringer -type OpType"; DO NOT EDIT.

package opr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Neg-0]
	_ = x[Inv-1]
	_ = x[Inc-2]
	_ = x[Dec-3]
	_ = x[Spread-4]
	_ = x[Sum-5]
	_ = x[Sub-6]
	_ = x[Multi-7]
	_ = x[Div-8]
	_ = x[Rem-9]
	_ = x[Eq-10]
	_ = x[Neq-11]
	_ = x[Gt-12]
	_ = x[Gte-13]
	_ = x[Lt-14]
	_ = x[Lte-15]
	_ = x[And-16]
	_ = x[Or-17]
	_ = x[Return-18]
	_ = x[Continue-19]
	_ = x[Break-20]
}

const _OpType_name = "NegInvIncDecSpreadSumSubMultiDivRemEqNeqGtGteLtLteAndOrReturnContinueBreak"

var _OpType_index = [...]uint8{0, 3, 6, 9, 12, 18, 21, 24, 29, 32, 35, 37, 40, 42, 45, 47, 50, 53, 55, 61, 69, 74}

func (i OpType) String() string {
	if i < 0 || i >= OpType(len(_OpType_index)-1) {
		return "OpType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpType_name[_OpType_index[i]:_OpType_index[i+1]]
}
