// Code generated by "stringer -type Type"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Int-0]
	_ = x[Float-1]
	_ = x[Bool-2]
	_ = x[String-3]
	_ = x[List-4]
	_ = x[Set-5]
	_ = x[Map-6]
	_ = x[Func-7]
	_ = x[Identifier-8]
	_ = x[Namespace-9]
	_ = x[NativeFuncSet-10]
	_ = x[Selector-11]
}

const _Type_name = "IntFloatBoolStringListSetMapFuncIdentifierNamespaceNativeFuncSetSelector"

var _Type_index = [...]uint8{0, 3, 8, 12, 18, 22, 25, 28, 32, 42, 51, 64, 72}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
